export const LOAD_BUDGET = 'LOAD_BUDGET';
export const SET_ALL_BUDGETS = 'SET_ALL_BUDGETS';
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const EDIT_BUDGET = 'EDIT_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
