export const CREATE_EXPENSE_ITEM = 'CREATE_EXPENSE_ITEM';
export const EDIT_EXPENSE_ITEM = 'EDIT_EXPENSE_ITEM';
export const DELETE_EXPENSE_ITEM = 'DELETE_EXPENSE_ITEM';
export const LOAD_EXPENSE_ITEMS = 'LOAD_EXPENSE_ITEMS';
